In [14]:
import pandas as pd

ages = pd.Series([23.5, 73, 23, 14, 14, 56, 39, 41])
ages


0    23.5
1    73.0
2    23.0
3    14.0
4    14.0
5    56.0
6    39.0
7    41.0
dtype: float64

# sample with random_state=10


In [15]:

sample_10 = ages.sample(1, random_state=10)
sample_10

2    23.0
dtype: float64

**What .sample(1, random_state=10) does**

It asks the random number generator (RNG) to shuffle the indices [0,1,2,3,4,5,6,7] using the seed 10.

The RNG generates a deterministic “shuffled order” of indices.

For example (internally, something like this):

[2, 4, 0, 5, 7, 3, 1, 6]


**Then .sample(1) just takes the first index from that order: here 2.**

It looks up index 2 in your Series → value = 23.0

# sample with random_state=0


In [16]:
sample_0 = ages.sample(1, random_state=0)
sample_0

6    39.0
dtype: float64

Different seed → different shuffle order.
For example:
here seed is 0 and the shuffle order might be
[6, 1, 0, 3, 7, 2, 4, 5]

First index is 6 , thus the value associated with index 6 is = 39.0
